twilio/twilio-video-app-android

app/build.gradle
app/src/androidTest/java/com/twilio/video/app/e2eTest/BackgroundSupportTest.kt
app/src/androidTest/java/com/twilio/video/app/util/UiAutomatorExtensions.kt
app/src/community/java/com/twilio/video/app/VideoApplicationComponent.java
app/src/internal/java/com/twilio/video/app/VideoApplicationComponent.java
app/src/main/AndroidManifest.xml
app/src/main/java/com/twilio/video/app/VideoService.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/room/RoomEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomManager.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomManagerModule.kt
app/src/main/java/com/twilio/video/app/ui/room/VideoServiceModule.java
app/src/main/java/com/twilio/video/app/ui/room/VideoServiceSubcomponent.java
app/src/main/res/values/strings.xml
app/src/twilio/java/com/twilio/video/app/VideoApplicationComponent.java

Abstracted room state management from RoomActivity so the activity and VideoService can subscribe to room state. Audio and screen sharing now works in the background even if the RoomActivity has been destroyed.
- Created RoomManager to handle and emit room state to subscribers.
- Remove room management from RoomActivity.
- Made changes to RoomActivity to support configuration changes.
- Finish implementation of VideoService.
- Foreground service can be clicked to be taken back to the room.
- Manually tested against two physical Android devices to avoid regressions.
There are still a few bugs when performing config changes on the activity, but the activity can be killed and the participant will still publish audio and screen sharing tracks in the background.

Video Service Implementation and Room Abstraction

---

app/src/androidTest/java/com/twilio/video/app/e2eTest/PreferencesTest.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Fixed bug where default topology would be set to P2P when navigating to the settings screen.
- Change default value to group in preferences.xml
- Manual tested.
- Passed CI pipeline.
N/A

Fix p2p default topology bug

---

build.gradle

Upgrade kotlin and gradle plugins.
- Upgrade gradle plugin to 3.6.1.
- Upgrade kotlin gradle plugin to 1.3.70
- Manual validation.
- Passed CI.
N/A

Upgrade gradle and kotlin plugins

---

app/build.gradle
app/src/community/java/com/twilio/video/app/VideoApplicationComponent.java
app/src/community/java/com/twilio/video/app/data/CommunityTokenService.kt
app/src/community/java/com/twilio/video/app/ui/room/CommunityRoomManagerModule.kt
app/src/main/java/com/twilio/video/app/data/api/TokenService.kt
app/src/main/java/com/twilio/video/app/data/api/VideoAppService.kt
app/src/main/java/com/twilio/video/app/data/api/VideoAppServiceDelegate.kt
app/src/main/java/com/twilio/video/app/data/api/VideoAppServiceModule.java
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/room/RoomEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomManager.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomManagerModule.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/java/com/twilio/video/app/ui/room/VideoService.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/twilio/video/app/data/api/VideoAppServiceDelegateTest.kt
app/src/test/java/com/twilio/video/app/util/MainCoroutineScopeRule.kt

Replaced RxJava logic that retrieves a token from the TokenService with Kotlin Coroutines. I also introduced a ViewModel in between the RoomActivity and RoomManager as a first step to getting closer to an MVVM architecture. Executing coroutines from a ViewModel is also recommended as it manages its own coroutine scope that is tied to the view model's lifecycle.
The changes to the RoomActivity look large, but that's because I moved the methods related to fetching the token and connecting to a room over to the RoomManager. Mainly pay attention to where the connectToRoom function gets invoked in the connectButtonClick method and where the view model gets initialized in onCreate.
- Modified DI to allow injection of TokenService in the RoomManager.
- Swapped out RxJava with Coroutines within …

Introduce Coroutines and Viewmodel

---

app/src/androidTest/java/com/twilio/video/app/e2eTest/RoomTest.kt
app/src/androidTest/java/com/twilio/video/app/screen/LobbyScreen.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java

Fixed token error display regression when muting audio track before joining a room.
- Check null LocalAudioTrack before adding it to the list of LocalAudioTracks
- Added e2e regression tests
- Manual validation
- Passed CI
N/A

Token error regression fix

---

app/build.gradle
app/src/community/java/com/twilio/video/app/VideoApplicationComponent.java
app/src/community/java/com/twilio/video/app/auth/CommunityAuthModule.kt
app/src/community/java/com/twilio/video/app/auth/CommunityAuthenticator.kt
app/src/community/java/com/twilio/video/app/data/AuthServiceModule.kt
app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt
app/src/community/java/com/twilio/video/app/security/SecurePreferences.kt
app/src/community/java/com/twilio/video/app/security/SecurityModule.kt

Created a SecurePreferences class to handle encryption and decryption of the Twilio auth function passcode.
- Add new SecurePreferences class.
- Reference new SecurePreferences class wherever passcode preference is stored/loaded.
- Modify Dagger DI to inject SecurePreferences.
- Manually looked at device explorer on a device to ensure passcode is encrypted and is removed when logging out.
- Passed CI.
N/A

AHOYAPPS-396: Encrypt passcode

---

app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/room/RoomEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomManager.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/res/menu/room_menu.xml

Fixed local video and audio track publishing issues when backgrounding the app while attempting to connect to a room. This PR also includes a fix for [AHOYAPPS-352](https://issues.corp.twilio.com/browse/AHOYAPPS-352).
- Removed audio and video tracks from the ConnectOptionsBuilder, and delay publishing of tracks until connecting to a room.
- Ensured onStart is invoked before the observable method bindRoomEvents to ensure the camera track is setup properly before publishing to the room.
- Cleaned up initializeRoom method.
- Manually validated by following bug reproduction steps on 2 Android devices.
- Passed CI pipeline.
N/A

AHOYAPPS-430: No local video publishing when backgrounding

---

README.md

An iOS customer had a problem getting started and I think it was caused by skipping `twilio login`. After looking closer I realized that login really is separate from install and so it should be a separate step.

Add Twilio CLI login instructions

---

app/src/main/res/drawable/roundbutton.xml
app/src/main/res/drawable/splash_screen.xml
app/src/main/res/values/styles.xml
build.gradle

Fix crash when launching the app on devices below API 21.
- Update gradle plugin
- Change color references in themes
- Remove parent theme of login screen
- Launched app on Android 18 device and successfully connected to room.

AHOYAPPS-534 Fix crash on devices below 21

---

README.md
app/build.gradle
app/proguard-rules.pro

Fix a crash caused by the release build type obfuscating the Facebook conceal dependency.
- Add facebook conceal Proguard configuration to `proguard-pro.rules`
- Manually test communityRelease by logging in
- Pass CI pipeline
N/A

AHOYAPPS-579: Fix conceal release build type crash

---

app/build.gradle

Upgraded audioswitch to 0.1.3.
**Changelog**
Bug Fixes
- Fixed crash by adding a default bluetooth device name.

Upgrade audioswitch to 0.1.3

---

app/src/main/java/com/twilio/video/app/participant/ParticipantManager.kt
app/src/main/java/com/twilio/video/app/participant/ParticipantViewState.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/test/java/com/twilio/video/app/participant/ParticipantManagerTest.kt
app/src/test/java/com/twilio/video/app/ui/room/RoomViewModelTest.kt

https://issues.corp.twilio.com/browse/AHOYAPPS-583
https://issues.corp.twilio.com/browse/AHOYAPPS-675
`LocalVideoTrack` and `RemoteVideoTrack` priorities are now properly managed. The `VideoTrack` that is rendered in the primary participant view for remote participants is now set to a high track priority. The only exception is if the primary participant view is a result of a dominant speaker change, in which case the track priority is set to null.
- Added track priority to `LocalVideoTrack` publishing in the `RoomActivity`
- `RemoteVideoTrack` priorities are now managed in the `ParticipantManager`
- Added helper functions to retrieve properties in `ParticipantViewState`
- Passed CI pipeline
- Passed manual validation on a Pixel XL

Manage Video Track Priorities

---

app/gradle.properties
app/src/main/java/com/twilio/video/app/participant/ParticipantManager.kt
app/src/test/java/com/twilio/video/app/participant/ParticipantManagerTest.kt

https://issues.corp.twilio.com/browse/AHOYAPPS-703
Fixed an issue where the track priority is cleared on a participant when they are re rendered in the main view.
- Check if the new participant is the same as the old primary participant in the `setTrackPriority()` function.
- Increased Gradle JVM heap to allow building release variants without running into OOM exceptions
- Passed CI
- Manually validated on a Pixel XL

AHOYAPPS-703: Fix pinning with track priority bug 

---

.circleci/config.yml
app/src/androidTest/java/com/twilio/video/app/e2eTest/AppLinkRoomTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/BackgroundSupportTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/BaseE2ETest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/E2ETest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/LoginTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/PermissionTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/PreferencesTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/RoomTest.kt
app/src/androidTest/java/com/twilio/video/app/integrationTest/IntegrationTest.kt
app/src/androidTest/java/com/twilio/video/app/integrationTest/SettingsTest.kt
app/src/androidTest/java/com/twilio/video/app/util/TestUtil.kt
app/src/main/java/com/twilio/video/app/ui/room/ParticipantViewHolder.kt
app/src/main/java/com/twilio/video/app/ui/room/PrimaryParticipantController.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
ui-test-args.yaml

Fixed a bug where a remote screen share track is not displayed in the main participant view. Also fixed another bug where a muted remote video track renders a frozen frame opposed to the correct NO_VIDEO thumbnail view state. The integration instrumentation tests are now separated from the E2E tests and are run as a separate CI jobs and separate FTL test runs.
- Changed video track parameters to the correct order when calling the renderAsPrimary() function from the RoomActivity 
- Added additional null check to the setVideoState() extension function top render the NO_VIDEO view state
- Added e2e-tests and instrumentation-tests as separate FTL test runs and separate CI jobs
- Added E2ETest and IntegrationTest annotation classes to target the tests in FTL test runs
- [Bulleted summary of …

AHOYAPPS-702: Fix screen share display bug

---

app/src/main/java/com/twilio/video/app/ui/room/ParticipantView.java
app/src/main/res/layout/participant_view.xml
app/src/main/res/layout/participant_view_primary.xml

Update scale type to aspect fit
- Change the VideoTextureView to layout width and height to `wrap_content`
- Set the default scale type to ASPECT_FIT
- Manual validation between 3 participants with desktop participant sharing screen. (See attached screenshots.

AHOYAPPS-730 Update video view scale type to aspect fit

---

app/src/androidTest/java/com/twilio/video/app/e2eTest/PermissionTest.kt
app/src/androidTest/java/com/twilio/video/app/screen/LobbyScreen.kt
app/src/androidTest/java/com/twilio/video/app/util/UiAutomatorExtensions.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/room/RoomViewEffect.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewState.kt
app/src/main/java/com/twilio/video/app/util/PermissionUtil.kt
app/src/test/java/com/twilio/video/app/ui/room/RoomViewModelTest.kt

https://issues.corp.twilio.com/browse/AHOYAPPS-696
This PR fixes a bug where the app crashes when a user toggles the local camera video after denying the camera permission. The following bugs are also fixed as part of this PR.
* Primary Video View freezes after muting video in the lobby.
* The join button is enabled with an empty room name.
- Added a new RoomViewEvent, CheckLocalMedia, that checks the local media permission state
- Added new RoomViewState properties to track the permission state for local media
- Added PermissionUtil to handle permission state check
- Passed CI Pipeline
- Manually tested on PixelXL

AHOYAPPS-696: Fix permission crash when toggling local camera video

---

app/build.gradle
app/src/main/java/com/twilio/video/app/AudioSwitchModule.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/room/RoomViewEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewState.kt
build.gradle

Enhancements
- Changed the name of the `AudioDeviceSelector` class to `AudioSwitch`.
- Added the [MODIFY_AUDIO_SETTINGS](https://developer.android.com/reference/android/Manifest.permission#MODIFY_AUDIO_SETTINGS) to the library manifest so it can be automatically consumed by applications.
- Added `AudioSwitch.VERSION` constant so developers can access the version of AudioSwitch at runtime.
- Added `AudioSwitch.loggingEnabled` property so developers can configure AudioSwitch logging behavior at runtime. By default, AudioSwitch logging is disabled. Reference the following snippet to enable AudioSwitch logging:
```kotlin
val audioSwitch = AudioSwitch(context)
audioSwitch.loggingEnabled = true
audioSwitch.start { _, _ -> }
```

Upgrade to AudioSwitch 0.3.0

---

.circleci/config.yml
app/build.gradle
app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt
app/src/main/java/com/twilio/video/app/AudioSwitchModule.kt
app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt

1. Add support for longer passcode format. The old format only used 4 digits to generate the URL which was not unique enough and some customers were running into conflicts. The only difference from an end user perspective is the passcode is now 14 digits instead of 10.
1. This is still backwards compatible with the shorter passcode format.
1. Using the latest [token server](https://github.com/twilio/twilio-video-app-android#deploy-twilio-access-token-server) with older versions of the Android video app will produce an error when the user enters the passcode. The solution is to update to the latest version to include changes in this PR.
* Also updated AudioSwitch dependency to [0.4.0](https://github.com/twilio/audioswitch/releases/tag/0.4.0).

AHOYAPPS-806: Add new passcode format

---

app/src/community/java/com/twilio/video/app/auth/CommunityAuthenticator.kt
app/src/community/java/com/twilio/video/app/data/AuthServiceModule.kt
app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt
app/src/community/java/com/twilio/video/app/data/api/AuthServiceResponseDTO.kt
app/src/community/java/com/twilio/video/app/data/api/RoomType.kt
app/src/main/java/com/twilio/video/app/android/SharedPreferencesWrapper.kt
app/src/main/java/com/twilio/video/app/data/Preferences.kt
app/src/main/java/com/twilio/video/app/data/api/model/Topology.kt
app/src/main/java/com/twilio/video/app/ui/settings/InternalSettingsFragment.kt
app/src/main/java/com/twilio/video/app/util/SharedPreferencesExtensions.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/internal_preferences.xml
app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt
app/src/testCommunity/java/com/twilio/video/app/ui/login/CommunityLoginActivityTest.kt

This PR adds changes to the community `AuthServiceRepository` to now check the [token server](https://github.com/twilio-labs/plugin-rtc#token-server-api-documentation) room-type and set the preferred video codec for an optimized experience based on the type of room. The Vp8 video codec is configured for all room types, but simulcast is disabled for the peer-to-peer room type. 
**Note:** The video codec configuration can be changed in the advanced settings screen in the app, but keep in mind that the video codec will be changed automatically every time the app detects a room type change from the token server.
- Passed CI.
- Manually validated that the codec changes are correct based on changes in room type from the token server.
Also made the following improvements:
1. Added a single …

AHOYAPPS-829: Optimize for P2P

---

app/src/main/java/com/twilio/video/app/adapter/StatsListAdapter.kt
app/src/main/java/com/twilio/video/app/data/Preferences.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
app/src/main/java/com/twilio/video/app/ui/settings/AdvancedSettingsFragment.kt
app/src/main/java/com/twilio/video/app/ui/settings/InternalSettingsFragment.kt
app/src/main/res/layout/stats_layout.xml

Enable stats by default and fix a bug in the stats UI.
- Connected to room and validated stats UI

Enable stats by default

---

app/src/androidTest/AndroidManifest.xml
app/src/androidTest/java/com/twilio/video/app/e2eTest/LoginTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/PreferencesTest.kt
app/src/androidTest/java/com/twilio/video/app/e2eTest/RoomTest.kt
app/src/androidTest/java/com/twilio/video/app/espresso/DrawableMatchers.kt
app/src/androidTest/java/com/twilio/video/app/espresso/HiddenView.kt
app/src/androidTest/java/com/twilio/video/app/screen/LobbyScreen.kt
app/src/androidTest/java/com/twilio/video/app/util/EspressoUtil.kt
app/src/androidTest/java/com/twilio/video/app/util/TestUtil.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt
app/src/main/res/drawable/ic_bluetooth_white_24dp.xml
app/src/main/res/drawable/ic_devices_white_24dp.xml
app/src/main/res/drawable/ic_headset_mic_white_24dp.xml
app/src/main/res/drawable/ic_phonelink_ring_white_24dp.xml
app/src/main/res/drawable/ic_volume_up_white_24dp.xml
app/src/main/res/menu/room_menu.xml

The audio device menu item now matches the state of the selected audio device from AudioSwitch.
- Passed CI.
Added `DrawableMatcher` to allow asserting a matching drawable in UI tests.

Add audio device change icons

---

app/build.gradle

Update to [Video Android 5.11.0](https://www.twilio.com/docs/video/changelog-twilio-video-android#5110-september-16th-2020)

Update to Video Android 5.11.0

---

app/build.gradle

Enhancements
- Upgraded Kotlin to `1.4.0`.
- Improved the Bluetooth headset connection and audio change reliability by registering the `BluetoothHeadset.ACTION_CONNECTION_STATE_CHANGED` and `BluetoothHeadset.ACTION_AUDIO_STATE_CHANGED` intent actions instead of relying on `android.bluetooth.BluetoothDevice` and `android.media.AudioManager` intent actions.
- The context provided when constructing `AudioSwitch` can now take any context. Previously the `ApplicationContext` was required.
Bug Fixes
- Added the internal access modifier to the `SystemClockWrapper` class since it is not meant to be exposed publicly.
- Passed CI.
- Manually validated on a Huawei P30 Lite.

Upgrade AudioSwitch to 1.0.1

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/layout-v21/activity_room.xml

The app now targets Android API 30 with support for screen share.
- Passed CI.

AHOYAPPS-837: Support screen share when targeting Android 10+

---

README.md
app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt
app/src/main/java/com/twilio/video/app/data/api/model/Topology.kt
app/src/main/java/com/twilio/video/app/sdk/LocalParticipantListener.kt
app/src/main/java/com/twilio/video/app/sdk/RemoteParticipantListener.kt
app/src/main/java/com/twilio/video/app/sdk/RoomManager.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewEffect.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/twilio/video/app/ui/room/RoomViewModelTest.kt
app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt

This PR contains support for the Programmable Video Go room type. The Go room type provides a similar peer-to-peer video app experience except for a smaller limit of two participants. If more than two participants join a room with this room type, then the video app will present an error. To learn more about Go, please visit the [Twilio blog](https://www.twilio.com/blog/announcing-twilio-video-webrtc-go).
- Manually validated each room type in the community flavor.
- Pass CI.

Implement Go Room Type Support

---

app/src/androidTest/java/com/twilio/video/app/e2eTest/RoomTest.kt
app/src/androidTest/java/com/twilio/video/app/util/EspressoUtil.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewEvent.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/main/res/layout/participant_view_primary.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/twilio/video/app/ui/room/RoomViewModelTest.kt
ui-test-args.yaml

This PR Fixes the following bugs:
1. The camera video is not rendered in the primary view when the app starts.
2. The app crashes when pinning the local participant video thumbnail and turning off the video track.
- Passed CI.
- Manual validation on a Huawei P30 Lite and Pixel 4.

AHOYAPPS-889: Camera not rendered when launching app for the first time

---

app/build.gradle
app/src/main/java/com/twilio/video/app/AudioSwitchModule.kt

Enhancements
- Added a constructor parameter named `preferredDeviceList` to configure the order in which audio devices are automatically selected and activated when `selectedAudioDevice` is null.
```kotlin
val audioSwitch = AudioSwitch(application, preferredDeviceList = listOf(Speakerphone::class.java, BluetoothHeadset::class.java))
```
- Updated `compileSdkVersion` and `targetSdkVersion` to Android API version `30`.

Upgrade AudioSwitch to 1.1.0

---

app/build.gradle

Upgraded the Video SDK dependency to the latest stable version, [5.12.0](https://github.com/twilio/twilio-video-android/releases/tag/5.12.0).

Upgrade Video SDK dependency to 5.12.0

---

app/build.gradle

* Programmable Video Android SDK 5.13.0 [[bintray]](https://bintray.com/twilio/releases/video-android/5.13.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/5.13.0/)
Maintenance
- Added `VideoCapturer#setSurfaceTextureHelper`. This method enables SDK provided video capturers to capture to a surface texture using a public API rather than an internal method. While this method is public, capturing to a surface texture is currently only supported with `Camera2Capturer`, and `ScreenCapturer`. Capturing to a surface texture will be enabled in a future release.
Bug Fixes
- Fixed a race condition that could cause a crash or unnecessary web socket signaling reconnection.
- Fixed a bug where private IP address was not masked properly while publishing insights event.
Known issues
- …

Update to 5.13.0

---

app/build.gradle

* The SDK API docs now include documentation for classes defined in [tvi.webrtc](https://twilio.github.io/twilio-video-android/docs/6.0.0-beta2/tvi/webrtc/package-frame.html). For example, the `VideoCapturer` API docs will now provide a link to the base interface `tvi.webrtc.VideoCapturer`.
* `isRecording()` API now accurately reflects the current recording state of the `Room`. In the previous versions of the SDK, `isRecording()` could return false positives. The `onRecordingStarted(...)` and `onRecordingStopped(...)` callbacks will now be invoked when recording for at least a single track in the `Room` has started and stopped respectively.

Upgrade to video SDK 6.0.0-beta2

---

app/src/androidTest/java/com/twilio/video/app/integrationTest/CameraCapturerCompatTest.kt
app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt
ui-test-args.yaml

Fixes a crash when using the `CameraCapturerCompat` from devices using the legacy `CameraCapturer`.
- Added legacy `CameraCapturer` compatible devices to FTL.
- Passed CI.

GSDK-2252: Fix CameraCapturerCompat Crash

---

app/build.gradle

* Programmable Video Android SDK 6.2.0 [[bintray]](https://bintray.com/twilio/releases/video-android/6.2.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.2.0/)
* Programmable Video Android SDK KTX 6.2.0 [[bintray]](https://bintray.com/twilio/releases/video-android-ktx/6.2.0), [[docs]](https://twilio.github.io/twilio-video-android/docs/ktx/6.2.0/)
* Updated the SDK to Android Gradle Plugin 4.1.1
* Removed `tvi.webrtc.NetworkMonitor` and `tvi.webrtc.NetworkMonitorAutoDetect` from the `libwebrtc.jar` since they are unused by the SDK.
Size Report
| ABI             | APK Size Impact |
| --------------- | --------------- |
| x86             | 5.5MB           |
| x86_64          | 5.5MB           |
| armeabi-v7a     | 4.1MB           |
| arm64-v8a       | 5.2MB           |
| …

Update video sdk to 6.2.0

---

app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt

Fixed Snackbar length lint error.
- Manually validated snackbar appears when denying the screen capture permission
- Passed CI

Fix Snackbar length lint error

---

app/build.gradle

* Programmable Video Android SDK 6.2.1 [[bintray]](https://bintray.com/twilio/releases/video-android/6.2.1), [[docs]](https://twilio.github.io/twilio-video-android/docs/6.2.1/)
* Fixed a crash that occurred while using either the `CameraCapturer` or `Camera2Capturer`, switching from the front camera to the back camera, and toggling the camera flash.
* Publishing multiple tracks with the same name results in a crash if network quality is enabled. To avoid this, use unique names for each track in the `Room`.
Size Report
| ABI             | APK Size Impact |
| --------------- | --------------- |
| x86             | 5.5MB           |
| x86_64          | 5.5MB           |
| armeabi-v7a     | 4.1MB           |
| arm64-v8a       | 5.2MB           |
| universal       | 19.6MB          |

Update video android to 6.2.1

---

.circleci/config.yml
app/build.gradle
app/src/main/java/com/twilio/video/app/sdk/RoomManager.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
app/src/test/java/com/twilio/video/app/ui/room/RoomViewModelTest.kt
build.gradle

Replaced the Kotlin Coroutine Channel with SharedFlow within the RoomManager class to emit video SDK events. SharedFlow is preferred over channels to handle asynchronous streams of events because of it's simplified API and direct compatibility with Flows. If we add additional Flows that the ViewModel consumes, we can perform flow operations like combine to easily integrate multiple streams of events.
This PR also includes an update to the Android Gradle Plugin.
- Manually validated video SDK features in the app
- Passed CI

Replace Coroutine Channel with SharedFlow

---

app/build.gradle

Enhancements
- Updated the library to use Android Gradle Plugin 4.1.1
- Now published to MavenCentral

Upgrade audioswitch to 1.1.2

---

app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt
chat/src/main/java/com/twilio/video/app/chat/ChatEvent.kt
chat/src/main/java/com/twilio/video/app/chat/ChatManager.kt
chat/src/main/java/com/twilio/video/app/chat/ChatManagerImpl.kt
chat/src/main/java/com/twilio/video/app/chat/sdk/MessageWrapper.kt
chat/src/test/java/com/twilio/video/app/chat/ChatManagerImplTest.kt

Adds the ability for the `ChatManager` to send a new text message via the conversations SDK.
- Validated manually via the rtc video plugin and the community app flavor.
- Passes CI.

VIDEO-3725: Chat Integration Layer - Send Message

---

build.gradle

Move mavenCentral() above jcenter() in the project level build.gradle repositories block.

VIDEO-4537: Move mavenCentral() above jcenter()

---

app/build.gradle

- Programmable Video Android SDK 6.3.0 [Maven Central](https://search.maven.org/artifact/com.twilio/video-android/6.3.0/aar), [Docs](https://twilio.github.io/twilio-video-android/docs/6.3.0/)
- Programmable Video Android SDK KTX 6.3.0 [Maven Central](https://search.maven.org/artifact/com.twilio/video-android-ktx/6.3.0/aar), [Docs](https://twilio.github.io/twilio-video-android/docs/ktx/6.3.0/)
- 100 Participant Group Rooms Pilot Program: A Group Room created with max participants greater than 50 is structured to support a small number of presenters and a large number of viewers. It has the following behavioral differences compared to regular Group Rooms:
- The `RoomListener.onParticipantConnected()` callback method is invoked when a `RemoteParticipant` connects to the Room and publishes at …

Consume latest video android 6.3.0

---

app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt
app/src/community/java/com/twilio/video/app/data/api/AuthServiceRequestDTO.kt
app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt

Added required `create_room` plugin-rtc HTTP request attribute as part of the chat feature release changes.
- Manually validated community build login and joining a room with another participant

Add required create_room plugin-rtc request attribute

---

app/src/main/java/com/twilio/video/app/VideoApplication.kt

Remove `WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true)` since it is automatically set in the SDK.
- Passes CI

Remove OpenSLES config

---

app/src/androidTest/java/com/twilio/video/app/integrationTest/PreferenceIntegrationTest.kt
app/src/main/java/com/twilio/video/app/data/Preferences.kt
app/src/main/java/com/twilio/video/app/sdk/ConnectOptionsFactory.kt
app/src/main/java/com/twilio/video/app/ui/settings/AudioSettingsFragment.kt
app/src/main/res/layout/participant_primary_view.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/advanced_preferences.xml
app/src/main/res/xml/audio_preferences.xml

Added advanced audio preferences. The preferences toggle the following WebRTC APIs:
```kotlin
WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(preference)
WebRtcAudioUtils.setWebRtcBasedNoiseSuppressor(preference)
WebRtcAudioUtils.setWebRtcBasedAutomaticGainControl(preference)
WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(preference)
```
- Passes CI.
- Manually validated preferences.

Add Advanced Audio Preferences

---

app/src/main/res/xml/advanced_preferences.xml
app/src/main/res/xml/internal_preferences.xml

Moved record control preference to internal flavor only as reported in #209 .
- Manually tested both app build flavors.
- Passes CI.

Move record control preference to internal flavor only

---

app/build.gradle
app/src/main/java/com/twilio/video/app/sdk/ConnectOptionsFactory.kt
app/src/main/java/com/twilio/video/app/ui/room/ParticipantView.java
app/src/main/java/com/twilio/video/app/ui/room/ParticipantViewHolder.kt
app/src/main/java/com/twilio/video/app/ui/room/PrimaryParticipantController.kt
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Made changes to consume the Client Track Switch Off feature from the Android Video SDK.
- The `VideoTextureView` property is exposed in the `ParticipantView` to add as a `RemoteVideoTrack` sink to benefit from the client track switch off auto mode.
- Fixed a bug in `PrimaryParticipantController` where a new sink was added every time even for the same video track.
- Updated the Gradle plugins and a couple of app dependencies.
- Replaced the internal bintray repository with artifactory to consume Video SDK RCs.
- Manually validated that tracks are switched on an off as expected with the new SDK feature.
- Passes CI.
There will be a follow up ticket to fix an issue in the SDK where switch offs do not occur when a view is detached from a ViewGroup.

VIDEO-5215: Update the Ahoy App to consume Client Track Switch Off Control

---

app/build.gradle

* Fixed a crash (see stacktrace below) that sometimes occurs on Pixel devices when decoding VP8 video streams.
```
java.lang.IllegalArgumentException: Texture width must be positive, but was 0
FATAL EXCEPTION: AndroidVideoDecoder.outputThread
Process: com.twilio.video.test, PID: 13001
java.lang.IllegalArgumentException: Texture width must be positive, but was 0
at tvi.webrtc.SurfaceTextureHelper.setTextureSize(SurfaceTextureHelper.java:256)
at tvi.webrtc.AndroidVideoDecoder.deliverTextureFrame(AndroidVideoDecoder.java:432)
at tvi.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:407)
at tvi.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:369)
```
* Fixed a bug that could cause a crash when changing log level to Trace at runtime.

Video Android 6.3.1

---

.circleci/config.yml
build.gradle
gradle.properties

Use the `sed` command to only change the versionCode in the `gradle.properties` file so the `android.useAndroidX` and `android.enableJetifier` properties do not get overwritten.
- Tested the gradle task in Circle CI on a separate branch

Fix version code bump script

---

CHANGELOG.md
app/build.gradle

- The SDK now supports audio only rooms and added two error codes, ROOM_AUDIO_ONLY_FLAG_NOT_SUPPORTED_EXCEPTION (53124) & TRACK_TRACK_KIND_NOT_SUPPORTED_EXCEPTION (53125).
- Improved reconnection time after network connectivity disruptions.
- As of 6.0.0 of the SDK, hardware video encoding doesn't publish all of the three simulcast layers when VP8 simulcast is enabled on Android.
This affects Video Content Preferences from working properly for subscribing video participants since the feature requires all three simulcast layers to switch between.
Our team is working on a fix for this, but the feature does work when VP8 simulcast is used to publish video from participants using the Javascript or iOS SDKs.
- Video Content Preferences might prefer larger video than needed when device …

Use Android Video 7.0.2

---

.circleci/config.yml
app/src/androidTest/java/com/twilio/video/app/e2eTest/BaseE2ETest.kt
app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt
app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt
ui-test-args.yaml

This PR introduces a number of fixes and enhancements related to the FTL test automation and Circle CI pipelines:
- Replace/update deprecated FTL test devices
- Publish test output from FTL runs to Circle CI
- Refactor and update Circle CI config
- remove/replace obsolete device/API combinations
- remove pre-LOLLIPOP checks in code, since minSdk is now 21
- refactor circleci config to use commands and executors
- add build steps to publish FTL test output to a gcloud bucket
- add build steps to retrieve FTL test output from gcloud bucket and publish to Circle CI as test results and artifacts
- use small executor for FTL tests
- replace deprecated circlci/android docker image with new cimg variant
- Circle CI runs show FTL test results and publish test output as artifacts.
E2E tests are …

VIDEO-7914: Various FTL test run fixes

---

CHANGELOG.md
app/build.gradle

* Programmable Video Android SDK 7.0.3 [[Maven Central]](https://search.maven.org/artifact/com.twilio/video-android/7.0.3/aar), [[docs]](https://twilio.github.io/twilio-video-android/docs/7.0.3/)
* Programmable Video Android KTX SDK 7.0.3 [[Maven Central]](https://search.maven.org/artifact/com.twilio/video-android-ktx/7.0.3/aar), [[docs]](https://twilio.github.io/twilio-video-android/docs/ktx/7.0.3/)
- Added error code definition `PARTICIPANT_SESSION_LENGTH_EXCEEDED_EXCEPTION`.
- Fixed a bug where if an exception occurs when connecting to a Room, the Room instance could leak and setting a custom audio device could fail.
- Fixed a bug where media could incorrectly be detected as not flowing after the network connectivity changes.
- As of 6.0.0 of the SDK, hardware video encoding doesn't …

Consume Video Android SDK 7.0.3

---

CHANGELOG.md
app/build.gradle
app/src/androidTest/java/com/twilio/video/app/e2eTest/BaseE2ETest.kt
app/src/androidTest/java/com/twilio/video/app/espresso/DrawableMatchers.kt
app/src/androidTest/java/com/twilio/video/app/screen/LoginScreen.kt
app/src/androidTest/java/com/twilio/video/app/util/UiAutomatorExtensions.kt

Fixed e2e test cases so that they are able to pass again on modern devices.
- Updated search UI string for enable/disable of permissions
- Updated matcher to do a bitmap compare of drawables because as of Android 21, using ConstantState as a proxy for equality is no longer supported (https://stackoverflow.com/questions/9125229/comparing-two-drawables-in-android)
- Updated test cases to wait for Firebase AuthUI to run its login activity before attempting to inject username/password  for test cases.
- Ran AndroidTest test cases on multiple devices
This does not fix all the flakiness, but is a large step in the right direction.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the …

fix e2e failing test cases

---

app/src/main/java/com/twilio/video/app/sdk/ConnectOptionsFactory.kt
app/src/main/java/com/twilio/video/app/ui/settings/AdvancedSettingsFragment.kt

Remove iSAC codec references
- Remove iSAC codec references

Remove iSAC codec references, webrtc 112

---

.circleci/config.yml

App should have build and e2e test every two weeks to check if everything works as expected. 
Adding e2e test workflow and pipeline parameter filter for biweekly e2e test runs.
Biweekly pipeline trigger - [here](https://app.circleci.com/settings/project/github/twilio/twilio-video-app-android/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Ftwilio%2Ftwilio-video-app-android&triggerSource=&scheduledTriggerId=52f291f5-0420-41de-8927-6cec3f6f9833)
- Add biweekly_run pipeline parameter to filter our workflows 
- Add biweekly-e2e-run workflow that runs every two weeks
- Check that biweekly-e2e-run workflow is not executed with the standard automatic PR workflows, and that those workflows and jobs are executed as expected/usual. …

Add biweekly e2e workflow run

---

.circleci/config.yml
app/build.gradle
build.gradle

Because this codebase is public, lets hide the Firebase App ID
- Hide the firebase app ID in an environment variable
- Published
None

Hide Firebase App ID

---

CHANGELOG.md
app/build.gradle
app/src/main/java/com/twilio/video/app/sdk/ConnectOptionsFactory.kt

Removed code that is no longer supported as of WebRTC-124.
- Commented out code that is no longer supported in WebRTC-124
- Built & Ran
Removed functionality will be added back via a different means at a different time. [VBLOCKS-3744]

Changes in preparation of WebRTC-124 upgrade

---

CHANGELOG.md
app/src/androidTest/java/com/twilio/video/app/integrationTest/PreferenceIntegrationTest.kt
app/src/main/java/com/twilio/video/app/data/Preferences.kt
app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/audio_preferences.xml

Instead of the audio options (Gain Control, echo cancelation, etc) being set by a webrtc singleton which was removed in WebRTC-124, its now being set as an audio option upon track construction.
- Now when the audio track is created, the audio options are set
- Removed OpenSLES option as it no longer applies to WebRTC-124
- Ran app and tested audio options
None

VBLOCKS-3744: audio options upon track construction

---

CHANGELOG.md
app/proguard-rules.pro

Fixed issue with unable to login with google account/gcloud for internal builds
- Added updated RSA app signing keys to firebase (no code change)
- Prevented Progaurd from obfuscating firebase libraries (from bug/ticket in firebase github, https://github.com/firebase/firebase-android-sdk/issues/4900#issuecomment-15200013)
- Ran both debug and release builds, signed with correct keys and was able to login
None

VBLOCKS-3919: gcloud login failure
