twilio/twilio-video-app-android

app/src/androidTest/java/com/twilio/video/app/e2eTest/BackgroundSupportTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/twilio/video/app/VideoService.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java, app/src/main/java/com/twilio/video/app/ui/room/RoomNotification.kt, app/src/main/java/com/twilio/video/app/ui/room/VideoService.kt, app/src/main/java/com/twilio/video/app/ui/room/VideoServiceModule.java, app/src/main/java/com/twilio/video/app/ui/room/VideoServiceSubcomponent.java, app/src/main/res/values/strings.xml
Improved UX of room background management notification and fixed a UI test issue.
- Abstracted notification logic from service.
- Add room name to notification.
- Modified notification wording.
- Add chronometer to notification.
- Fix BackgroundSupportTest by searching for the notification opposed to selecting the first index.
- Manually tested and passed CI pipeline.
N/A
=> Room Notification Improvements

app/build.gradle, app/lint-baseline.xml, app/src/main/java/com/twilio/video/app/ui/settings/SettingsActivity.kt, app/src/main/res/layout/activity_login.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Update gradle plugin to 3.6.0.
Update gradle plugin to 3.6.0
Passed CI pipeline.
N/A
=> Gradle plugin 3.6.0 update

app/src/main/res/xml/preferences.xml
Move topology to advanced settings
- Only internal variant can now only view topology setting
- Passed CI pipeline.
- Manual tested all build variants.
N/A
=> Move topology to advanced settings

app/lint-baseline.xml, app/src/community/java/com/twilio/video/app/ui/login/CommunityLoginActivity.java, app/src/community/res/layout/development_activity_login.xml, app/src/community/res/values/strings.xml, app/src/main/java/com/twilio/video/app/ui/login/LoginActivity.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java, app/src/main/res/drawable/roundbutton.xml, app/src/main/res/drawable/splash_screen.xml, app/src/main/res/layout/fragment_existing_account_login.xml, app/src/main/res/layout/fragment_login_landing.xml, app/src/main/res/layout/range_bar_preference.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Implemented the UI for the new on boarding experience. Also cleaned up some theming in the app along with fixing a community login navigation regression.
- Added TextInputEditTexts for user identity and the app code.
- Reference theme for coloring opposed to color resources directly
- Fixed community navigation after login regression.
- Passed CI.
- Manual validation on all variants.
N/A
=> AHOYAPPS-355: User identity and app code UI

app/build.gradle
Update to Video Android 5.1.1
- CI pipeline
=> Update to Video Android 5.1.1

app/build.gradle, app/src/community/java/com/twilio/video/app/auth/CommunityAuthenticator.kt, app/src/community/java/com/twilio/video/app/data/api/AuthServiceError.kt, app/src/community/java/com/twilio/video/app/data/api/AuthServiceErrorDTO.kt, app/src/community/java/com/twilio/video/app/data/api/AuthServiceException.kt, app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt, app/src/community/res/values/strings.xml, app/src/main/java/com/twilio/video/app/data/api/TokenService.kt, app/src/main/java/com/twilio/video/app/data/api/VideoAppServiceDelegate.kt, app/src/testCommunity/java/com/twilio/video/app/data/AuthServiceRepositoryTest.kt, app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt, app/src/testCommunity/java/com/twilio/video/app/screen/CommunityLoginScreen.kt, app/src/testCommunity/java/com/twilio/video/app/ui/login/CommunityLoginActivityTest.kt, app/src/testCommunity/java/com/twilio/video/app/util/AuthServiceTestData.kt
Added happy path community login integration tests and began implementation of detailed error handling for Twilio auth function.
- Add happy path integration tests for CommunityLoginActivity.
- Add data classes and custom exception for Twilio auth function error handling.
- Passed manual validation and CI pipeline.
N/A
=> AHOYAPPS-371: Onboarding Implementation

app/build.gradle, app/lint-baseline.xml, app/src/main/java/com/twilio/video/app/VideoApplication.kt, app/src/main/java/com/twilio/video/app/ui/room/ParticipantController.java, app/src/main/java/com/twilio/video/app/ui/room/ParticipantView.java, app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java, app/src/main/java/com/twilio/video/app/ui/room/RoomManager.kt, app/src/main/res/layout/participant_view_primary.xml
Video app UI implementation of the remote network quality level Video SDK feature.
- Enabled RNQL in the RoomManager
- Set remote participant listener when adding remote participants as thumbnails or primary view to allow rendering of RNQL
- Adjusted primary badge icon layout
- Manually tested in a room with 3 devices.
@aaalaniz Shall we mark this as 1.0.0 for the app version and update the changelog?
=> AHOYAPPS-438: Implement remote network quality

app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.java
Added an image for Network Quality Level 0.
Added an image for Network Quality Level 0.
- Manually tested.
-Passed CI.
N/A
=> Add an image for Network Quality Level 0

app/build.gradle, app/src/main/res/layout/content_room.xml
Update to Video Android 5.4.0
- FTL run
=> Update to Video Android 5.4.0

README.md
Add disclaimer in readme about token server.
- Add disclaimer in readme about token server.
N/A
N/A
=> AHOYAPPS-539: Add token server disclaimer

app/build.gradle
=> Update AudioSwitch to 0.1.1

app/build.gradle
Upgraded AudioSwitch library to 0.1.2.
=> Upgrade AudioSwitch library to 0.1.2

app/build.gradle
Upgraded to latest video SDK RC, 5.8.0-rc2.
- Passed CI
=> Upgrade to video SDK 5.8.0-rc2

app/src/main/java/com/twilio/video/app/TreeModule.java, app/src/main/java/com/twilio/video/app/participant/ParticipantManager.kt
Enable logging for the internal build flavor.
=> Enable internal build flavor logging

README.md
Added a bullet point that links to the BWP wiki from the feature bullet list section.
=> Add BWP feature reference to README

app/build.gradle
Upgraded the AudioSwitch dependency to 0.1.4.
Enhancements
- AAR minification is now enabled for release artifacts.
Bug Fixes
- Fixed a bug where the audio output doesn't automatically route to a newly connected bluetooth headset.
- Fixed a bug where the selected audio device doesn't get routed back to the default audio device when an error occurs when attempting to connect to a headset.
=> Upgrade to AudioSwitch 0.1.4

app/build.gradle
Bug Fixes
- Disabled AAR minification to fix Android Studio issues such as getting stuck in code analysis and not being able to find declarations of AudioSwitch code.
=> Upgrade to audioswitch 0.1.5

README.md
Added Android 11 roadmap link.
=> Add Android 11 roadmap link to readme

README.md
Minor tweek on the notice to be consistent with other notices we've added in other projects.
=> Block indent notice

build.gradle
Push versionCode as tag after merge to master
=> AHOYAPPS-834 Push versionCode as tag after merge to master

build.gradle, gradle.properties
=> Fix auto tagging

app/build.gradle
Promotes 0.4.0 to the first stable release of this library.
=> Upgrade to AudioSwitch 1.0.0

app/build.gradle
Update to [Video Android 5.10.2](https://www.twilio.com/docs/video/changelog-twilio-video-android#5102-august-18th-2020)
=> Update to Video Android 5.10.2

build.gradle
=> Upgrade Kotlin to 1.4.0

README.md
Added a section in the readme to explain how the different room types affect the app's behavior.
=> AHOYAPPS-871: Document video app room type behavior 

app/build.gradle
Update to [Video Android 5.11.1](https://www.twilio.com/docs/video/changelog-twilio-video-android#5111-september-22nd-2020)
=> Update to Video Android 5.11.1

app/build.gradle, app/lint-baseline.xml, app/src/main/java/com/twilio/video/app/util/CrashlyticsTreeRanger.java, build.gradle
Migrate from Crashlytics to FirebaseCrashlytics to resolve lint errors. I also updated the lint-baseline.xml after fixing this error so the lint errors to fix is accurate.
- CI
=> AHOYAPPS-888 Update to FirebaseCrashlytics

app/build.gradle, app/src/main/AndroidManifest.xml
Added camera and microphone foreground service type as part of [Android 11 requirements](https://developer.android.com/guide/components/foreground-services#types).
- Passed CI.
=> Add camera and microphone foreground service type

app/build.gradle, app/src/main/AndroidManifest.xml
Reverted camera and microphone foreground service types as they have no affect on the video app.
=> Revert camera and mic foreground service type

app/build.gradle, app/src/main/java/com/twilio/video/app/util/CrashlyticsTreeRanger.java, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Upgraded to the latest AppCenter release to fix in-app updates when targeting API 30.
- Passed CI
=> Upgrade to latest AppCenter SDK

app/build.gradle, app/src/community/java/com/twilio/video/app/data/api/AuthServiceRepository.kt, app/src/main/java/com/twilio/video/app/data/Preferences.kt, app/src/main/java/com/twilio/video/app/data/RangeBarPreference.kt, app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt, app/src/main/java/com/twilio/video/app/ui/room/ParticipantView.java, app/src/main/java/com/twilio/video/app/ui/room/ParticipantViewHolder.kt, app/src/main/java/com/twilio/video/app/ui/room/PrimaryParticipantController.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt, app/src/main/java/com/twilio/video/app/ui/settings/AdvancedSettingsFragment.kt, app/src/main/res/layout/range_bar_preference.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/xml/advanced_preferences.xml, app/src/testCommunity/java/com/twilio/video/app/data/api/AuthServiceRepositoryTest.kt, scripts/gen_errors.sh, scripts/send-circleci-webhook.sh
Revert 6.0.0-preview1 work as it should be in a feature branch for now.
- Passed CI
=> Revert "Video SDK 6.0.0-preview1 (#162)"

app/build.gradle, app/src/main/java/com/twilio/video/app/sdk/ConnectOptionsFactory.kt, app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt
Adopted the KTX library.
- Passed CI pipeline.
=> VAKTX-16: Adopt KTX library

app/src/main/java/com/twilio/video/app/data/NumberPreferenceDialogFragmentCompat.java
Replace print stack trace with Timber log
- CI
=> GSDK-2246 Replace print stack trace with Timber log

app/src/community/java/com/twilio/video/app/data/api/AuthServiceRequestDTO.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomActivity.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomViewEvent.kt, app/src/main/java/com/twilio/video/app/ui/room/RoomViewModel.kt, app/src/main/res/drawable/ic_chat.xml, app/src/main/res/layout-v21/room_activity.xml, app/src/main/res/layout/room_activity.xml, chat/build.gradle, chat/src/main/java/com/twilio/video/app/chat/ChatManager.kt, chat/src/main/java/com/twilio/video/app/chat/ChatManagerImpl.kt, chat/src/main/java/com/twilio/video/app/chat/ChatState.kt, chat/src/test/java/com/twilio/video/app/chat/ChatManagerImplTest.kt
Completes the integration layer work by adding support for reading in new messages and handles state management regarding when messages are considered unread by the `ChatManager`.
- Passed CI
- Manually test sending and receiving new messages
=> VIDEO-3720: Chat Integration Layer - Read New Messages

app/build.gradle
Upgrade dagger to fix a lint error in the pipeline.
- Passes CI
=> Upgrade Dagger

app/build.gradle
Consumes the latest Media Optimizations RC ([6.4.0 rc3](https://github.com/twilio/twilio-video-android/releases/tag/6.4.0-rc3))
- Passes CI
=> Consume latest Media Optimizations RC (6.4.0 rc3)

.github/PULL_REQUEST_TEMPLATE.md
This PR removes the redundant check list items from the PR GitHub template.
=> Remove redundant check list items

app/build.gradle
Update to Android Video version 6.4.1
* Fixed a crash when `maxTracks` or `renderDimensions` is set and a sink is added for a `RemoteVideoTrack`.
- [Bulleted summary of changes]
- [eg. Add new public function to `Authenticator.kt` ]
- [eg. Add new string resources to `strings.xml`]
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]
=> Use Android Video 6.4.1

CHANGELOG.md, app/build.gradle
Upgraded the version of audioswitch used.
- Upgraded audioswitch to 1.1.4
- ran test cases
N/A
=> Updated audioswitch

app/build.gradle
Updated the version of Android SDK used
- Updated android sdk version 7.0.6 (latest)
- ran app
None
=> Updated to use the latest release of the SDK

CHANGELOG.md, app/build.gradle, build.gradle
-Updated sdk version to 7.1.0
- Updated sdk version to 7.1.0
- Updated google gradle tools to 7.0.4
- It Built & ran
=> VIDEO-9163 Updated SDK version

CHANGELOG.md, app/build.gradle
Updated twilio Android sdk to 7.1.1
- updated android sdk version
- built and ran
none
=> Updated twilio android sdk version to 7.1.1

CHANGELOG.md, app/build.gradle
Updated audioswitch version
- Updated audioswitch version
- Ran app & tests
=> VIDEO-10373 Updated audioswitch version

CHANGELOG.md, app/build.gradle
Updated android sdk version to 7.1.2
- Updated Android sdk version to latest release (7.1.2).
- Built and tested
None
=> Updated android-sdk version 7.1.2

.circleci/config.yml, app/build.gradle
=> Update SDK to 7.6.1

app/build.gradle
Updated sdk version
- [Bulleted summary of changes]
- [eg. Add new public function to `Authenticator.kt` ]
- [eg. Add new string resources to `strings.xml`]
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]
=> Updated sdk version

CHANGELOG.md
Updated changelog to reflect changes in preparation for release
- Modified changelog
N/A
None
=> VIDEO-12967: Updated changelog for release

app/build.gradle
updated sdk to 7.6.4 (latest release)
- above
- built
None
=> updated sdk to 7.6.4

app/build.gradle, app/gradle.properties, app/src/main/AndroidManifest.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, ui-test-args.yaml
Upgraded AGP version
- Updated AGP version
- ran tests
None
=> VBLOCKS-2901: upgrade agp version

README.md
Updated the date of the Video EOL by two years.
- Updated readme
None
None
=> VBLOCKS-2958: updated banner eol date

CHANGELOG.md, app/build.gradle, gradle.properties
Updated version
- updated version for appcetner publish
- ran tests
none
=> Afalls/vblocks 3426/updated sdk

README.md
=> VBLOCKS-3615 - Removed EOL banner

README.md
Removed legacy Room types
- [Bulleted summary of changes]
- [eg. Add new public function to `Authenticator.kt` ]
- [eg. Add new string resources to `strings.xml`]
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]
=> Removed legacy Room types

.circleci/config.yml, app/build.gradle, build.gradle
Modified to support publishing from Video SDK using the Video SDK Version
- Added a property for version name 
- Releases now use this property if it exists
- Built & published
None
=> [VBLOCKS-3660] Modify to support publishing RC version from Video SDK

CHANGELOG.md, app/build.gradle
Upgraded to target API 35
- upgraded to target API 35
- Built and ran
None
=> Upgraded to API 35

CHANGELOG.md, app/build.gradle
Updated to use latest Video Android release, 7.8.0
- Updated Video Android Version
- compiled and ran
None
=> [VIDEO-4055] updated Video-Android version to 7.8.0
